dataset_configs:
  c10:
    dataset: cifar10
    root: /data/aquelennec
    new_num_classes: 10

  c100:
    dataset: cifar100
    root: /data/aquelennec
    new_num_classes: 100
  
  vww:
    dataset: vww
    root: /data/aquelennec
    new_num_classes: 2
  
  flowers:
    dataset: image_folder
    root: /data/aquelennec/flowers102
    new_num_classes: 102
  
  food:
    dataset: image_folder
    root: /data/aquelennec/food101
    new_num_classes: 101

  pets:
    dataset: image_folder
    root: /data/aquelennec/pets
    new_num_classes: 37

  cub:
    dataset: image_folder
    root: /data/aquelennec/cub200
    new_num_classes: 200


net_configs:
  scheme_1:
      ratio: 0.0878233231
      SU_scheme:
        n_bias_update: 16  # how many conv to update the bias
        weight_update_ratio: 1-1-0-0.25-0.125-0.125-0.125-0.125  # how many weights along input channels are updated (also support int number)
        manual_weight_idx: 36-39-40-41-42-45-48-49
    
  scheme_2:
    ratio: 0.1508110478
    SU_scheme:
        n_bias_update: 20  # how many conv to update the bias
        weight_update_ratio: 0.125-0.5-0.5-1-0.25-0.125-0.125-1  # how many weights along input channels are updated (also support int number)
        manual_weight_idx: 32-33-36-39-41-42-45-48

  scheme_3:
    ratio: 0.212187637
    SU_scheme:
        n_bias_update: 25  # how many conv to update the bias
        weight_update_ratio: 1-1-1-1-1-0.125-0.5-1  # how many weights along input channels are updated (also support int number)
        manual_weight_idx: 27-30-33-36-39-42-45-48

  scheme_4:
    ratio: 0.2735642262
    SU_scheme:
        n_bias_update: 31  # how many conv to update the bias
        weight_update_ratio: 1-1-1-1-1-0.5-1-1  # how many weights along input channels are updated (also support int number)
        manual_weight_idx: 27-30-33-36-39-42-45-48

  scheme_5:
    ratio: 0.3084995616
    SU_scheme:
        n_bias_update: 34  # how many conv to update the bias
        weight_update_ratio: 1-1-1-1-1-1-1-1  # how many weights along input channels are updated (also support int number)
        manual_weight_idx: 27-30-33-36-39-42-45-48
    
  scheme_6:
      ratio: 0.5
  
  scheme_7:
    ratio: 1


networks:
  mbv2:
    total_num_params: 2189760

  resnet18:
    total_num_params: 11166912

  resnet50:
    total_num_params: 23454912

  pre_trained_mbv2:
    total_num_params: 2189760

  pre_trained_resnet18:
    total_num_params: 11166912

  pre_trained_resnet50:
    total_num_params: 23454912